import { createSlice, configureStore } from '@reduxjs/toolkit';

const initialCounterState = {
  counter: 0,
  showCounter: true,
};

// createSlice is more powerful than createReducer
// can create different slices in different files
// the 4 methods will automatically be called depending which action was triggered
// allowed to mutate state because reduxtool kit internally make a copy of the state and we just change what we want to change here
const counterSlice = createSlice({
  name: 'counter',
  initialState: initialCounterState,
  reducers: {
    increment(state) {
      state.counter++;
    },
    decrement(state) {
      state.counter--;
    },
    increase(state, action) {
      state.counter = state.counter + action.payload;
    },
    toggleCounter(state) {
      state.showCounter = !state.showCounter;
    },
  },
});

const initialAuthState = {
  isAuthenticated: false,
};

const authSlice = createSlice({
  name: 'authentication',
  initialState: initialAuthState,
  reducers: {
    login(state) {
      state.isAuthenticated = true;
    },
    logout(state) {
      state.isAuthenticated = false;
    },
  },
});

// for toolkit, behind the scenes many reducers will be merged into one big reducer
const store = configureStore({
  reducer: { counter: counterSlice.reducer, auth: authSlice.reducer },
});

// toolkit automatically create action creators out of the methods; look like {type: 'some autogenerated unique identifier'}
// example counterSlice.actions.toggleCounter
// counterSlice.actions will use the same 'action dispatch' name as our reducer methods like increment, increase, etc
export const counterActions = counterSlice.actions;
export const authActions = authSlice.actions;

export default store;
